**BY ANARADO CHRISTIANA**

**Assignment for the week**

-Research and write down 20 in built method on pandas and 20 on numpy with examples each.

**1) write down 20 in built method on pandas.**

In [47]:
import pandas as pd

In [48]:
long_series = pd.Series(np.random.randn(1000))

In [49]:
long_series.head()

0    0.905727
1    0.933564
2   -0.976484
3    1.266932
4   -0.536180
dtype: float64

In [50]:
long_series.tail()

995   -0.223001
996    1.552633
997    0.388634
998   -1.299919
999   -1.415839
dtype: float64

In [51]:
long_series.loc[1]

0.9335638433326728

In [52]:
long_series.iloc[2]

-0.976483735273125

In [53]:
long_series.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: None
Non-Null Count  Dtype  
--------------  -----  
1000 non-null   float64
dtypes: float64(1)
memory usage: 7.9 KB


In [54]:
long_series.dtypes

dtype('float64')

In [55]:
long_series.describe()

count    1000.000000
mean       -0.013771
std         0.992787
min        -3.926010
25%        -0.693248
50%        -0.020398
75%         0.680416
max         2.730855
dtype: float64

In [56]:
long_series.sort_index

<bound method Series.sort_index of 0      0.905727
1      0.933564
2     -0.976484
3      1.266932
4     -0.536180
         ...   
995   -0.223001
996    1.552633
997    0.388634
998   -1.299919
999   -1.415839
Length: 1000, dtype: float64>

In [57]:
long_series.nunique()

1000

In [58]:
long_series.isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [59]:
long_series.memory_usage()

8128

In [60]:
long_series.value_counts()

 0.905727    1
-0.692786    1
 0.867552    1
 0.092650    1
-1.272442    1
            ..
 1.513794    1
 0.185341    1
 0.052687    1
-0.188004    1
-1.415839    1
Length: 1000, dtype: int64

In [61]:
long_series.sum()

-13.770997252551286

In [62]:
long_series.isna()

0      False
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [63]:
long_series.sample()

720   -0.661833
dtype: float64

In [64]:
long_series.shape

(1000,)

In [65]:
long_series.size

1000

In [66]:
long_series.dropna()

0      0.905727
1      0.933564
2     -0.976484
3      1.266932
4     -0.536180
         ...   
995   -0.223001
996    1.552633
997    0.388634
998   -1.299919
999   -1.415839
Length: 1000, dtype: float64

In [45]:
long_series.unique()

array([-8.78908918e-02, -1.31278716e+00,  3.07972226e-01, -5.76121755e-01,
        2.50173272e-01,  2.32602339e-01, -1.07469391e-01,  8.21918190e-02,
       -8.87857345e-01, -5.31956218e-01,  2.59097297e-01,  1.58473315e+00,
       -1.06005635e+00, -6.06385173e-01, -1.00914991e+00, -8.14186350e-01,
       -1.02628931e+00,  1.04694869e+00,  7.72369314e-01,  1.67717614e+00,
        7.23470058e-01, -1.35468607e-01,  2.76742338e-01, -1.63163022e-01,
       -3.77212508e-01,  2.33916255e-01, -1.46993789e+00, -7.84818137e-01,
        1.26624473e+00,  1.11447572e+00,  7.63420386e-01,  1.97308226e-01,
       -3.34535962e-01,  2.56564885e-01,  1.80694123e-01,  9.82657214e-01,
        2.89330893e-02, -9.64232058e-01,  4.97289002e-01, -2.14366964e+00,
        7.99671766e-01,  9.92857750e-01, -1.46725859e-01,  5.14455408e-02,
       -6.46030867e-02,  2.86906073e-01,  2.12242397e-01,  3.19519302e-01,
       -2.20806032e+00, -3.59894375e-01,  1.81314047e+00, -1.86105863e+00,
       -3.61641985e-02,  

**2) write down 20 in built method on numpy**

In [67]:
import numpy as np

In [68]:
a = np.array([1, 2, 3])

In [69]:
np.zeros(2)

array([0., 0.])

In [70]:
np.ones(2)

array([1., 1.])

In [71]:
np.empty(2)

array([1., 1.])

In [72]:
np.arange(4)

array([0, 1, 2, 3])

In [73]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [78]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
arr.ndim

1

In [81]:
arr.size

8

In [82]:
arr.shape

(8,)

In [88]:
arr.reshape

<function ndarray.reshape>

In [89]:
arr.dtype

dtype('int32')

In [90]:
arr.max()

8

In [91]:
arr.min()

1

In [92]:
arr.sum()

36

In [93]:
arr.mean()

4.5

In [95]:
arr.flatten()

array([2, 1, 5, 3, 7, 4, 6, 8])

In [102]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [104]:
np.random.randint(5)

3

In [99]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
c = np.append(a, b)  
print(c) 

[1 2 3 4 5 6 7 8]


In [109]:
np.argsort(c)

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)